GET  https://localhost:3001/tasks HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3IiwiaWF0IjoxNTg4MTc4NDM4LCJleHAiOjE1ODgxODIwMzh9.ZZabBr9m8X1kNWQp0n7IYqpgUVUJwYuh2gA4yDlOr8c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3VVNFUjIiLCJpYXQiOjE1ODkwOTU5OTIsImV4cCI6MTU4OTA5OTU5Mn0.7WmAO6F89qUnabwhpv7aAm1Qogfaro4HAiRtPYJ_074

{
    "username": "Mirko867",
    "password": "MirkoPe!23$@3asdawea"
}

###
POST https://localhost:3000/tasks HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3IiwiaWF0IjoxNTg4MTc4NDM4LCJleHAiOjE1ODgxODIwMzh9.ZZabBr9m8X1kNWQp0n7IYqpgUVUJwYuh2gA4yDlOr8c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3VVNFUjIiLCJpYXQiOjE1ODgxNzkyNDAsImV4cCI6MTU4ODE4Mjg0MH0.GVcuGdPvoPpUJ-DDfjUyJogS1XMktCgBrgAvldEJgJ4

{
    "title": "Call Jana",
    "description": "Check if lol",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET https://localhost:3000/tasks/f7dd94ac-0171-4b58-9591-1271bfab36af HTTP/1.1
content-type: application/json

{
    "title": "JavaScript",
    "description": "Is not the same",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET https://localhost:3000/tasks?status=OPEN&search=a HTTP/1.1
content-type: application/json

{
    "status": "OPEN",
    "search": "hello"
}
###
GET https://localhost:3000/tasks?status=IN_PROGRESS HTTP/1.1
content-type: application/json

{
    "status": "OPEN",
    "search": "hello"
}
###

DELETE https://localhost:3000/tasks/2 HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "description",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###

PATCH  https://localhost:3000/tasks/1/status HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "description",
    "status": "IN_PROGRESS",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

########### SIGN UP METHOD ############

###
POST https://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "Mirko867",
    "password": "MirkoPe!23$@3asdawea"
}


###
POST https://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "Mirko867",
    "password": "MirkoPe!23$@3asdawea"
}


###
POST https://localhost:3000/auth/test HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3IiwiaWF0IjoxNTg4MTc3NTcxLCJleHAiOjE1ODgxODExNzF9.YZARk2JjutxZ9cJ9wo-rXrEIfMhy-lP70qJI0Z4Z9oE

{
    "username": "Mirko867",
    "password": "MirkoPe!23$@3asdawea"
}


###
POST https://localhost:3000/auth/tests HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3IiwiaWF0IjoxNTg4MTc4NDM4LCJleHAiOjE1ODgxODIwMzh9.ZZabBr9m8X1kNWQp0n7IYqpgUVUJwYuh2gA4yDlOr8c

{
    "username": "Mirko867",
    "password": "MirkoPe!23$@3asdawea"
}



########### SIGN UP METHOD USER2 ############

###
POST https://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "CiccioPasticcio",
    "password": "CiccioPasticcio86"
}

###
POST https://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "CiccioPasticcio",
    "password": "CiccioPasticcio86"
}



###
POST https://localhost:3000/auth/test HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3VVNFUjIiLCJpYXQiOjE1ODgxNzkyNDAsImV4cCI6MTU4ODE4Mjg0MH0.GVcuGdPvoPpUJ-DDfjUyJogS1XMktCgBrgAvldEJgJ4

{
    "username": "Mirko867",
    "password": "MirkoPe!23$@3asdawea"
}


###
POST https://localhost:3000/auth/tests HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pcmtvODY3VVNFUjIiLCJpYXQiOjE1ODgxNzkyNDAsImV4cCI6MTU4ODE4Mjg0MH0.GVcuGdPvoPpUJ-DDfjUyJogS1XMktCgBrgAvldEJgJ4

{
    "username": "CiccioPasticcio",
    "password": "CiccioPasticcio86"
}