GET  http://localhost:5000/tasks HTTP/1.1
###
POST http://localhost:5000/tasks HTTP/1.1
content-type: application/json

{
    "title": "Call Sara",
    "description": "Check if she is all right.",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET http://localhost:3000/tasks/f7dd94ac-0171-4b58-9591-1271bfab36af HTTP/1.1
content-type: application/json

{
    "title": "JavaScript",
    "description": "Is not the same",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET http://localhost:5000/tasks?status=OPEN&search=a HTTP/1.1
content-type: application/json

{
    "status": "OPEN",
    "search": "hello"
}
###
GET http://localhost:3000/tasks?status=IN_PROGRESS HTTP/1.1
content-type: application/json

{
    "status": "OPEN",
    "search": "hello"
}
###

DELETE http://localhost:5000/tasks/2 HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "description",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###

PATCH  http://localhost:5000/tasks/1/status HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "description",
    "status": "IN_PROGRES",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}